import = [
    "~/.config/alacritty/themes/themes/pencil_dark.toml"
]


[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_title = false

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"
size = 14

[colors]
draw_bold_text_with_bright_colors = true
