import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]


[window]
decorations = "None"
# opacity = 0.9
startup_mode = "Maximized"

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"
size = 14

[colors]
draw_bold_text_with_bright_colors = true
